name: Check code quality

on:
  push:

jobs:
  action:
    name: python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Code quality check - ruff
        run: uv run ruff check --fix .
        
      - name: Code quality check - mypy
        run: uv run mypy mcp_server.py